spring:
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 3000 # 连接超时时间（毫秒
  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lcp-dev?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 
    #oracle配置
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: renren
    #    password: 123456
    #SQLServer配置
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL配置
    #    driverClassName: org.postgresql.Driver
    #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
    #    username: postgres
    #    password: 123456
    
  api:
    context: test
  cluster:
    gateway:
      name: apitest
  groovy-api:
    groovyscript:
      enabled: true
    config:
      sql: sql.xml
      datasource: datasource.xml
    service-title: API平台
    sql-model:
      find-one-suffix: /first
      pager-suffix: /page
      count-suffix: /count

file:
  #文件上传目录 绝对路径 末尾请加 /
  path: D:/files/ #windows
  #path: /data/files/ #linux
  #文件预览、下载的url, 末尾请勿加 /
  url: http://localhost:8080/files
  
config:
  api:
    context: apitest
    mode: 1
    serviceName: lcp-engine
    basePath: apiengine
  cluster:
    gateway:
      name: apitest
  
# AES密码加密私钥(Base64加密)
encryptAESKey: V2FuZzkyNjQ1NGRTQkFQSUpXVA==
# JWT认证加密私钥(Base64加密)
encryptJWTKey: U0JBUElKV1RkV2FuZzkyNjQ1NA==
# AccessToken过期时间-5分钟-5*60(秒为单位)
accessTokenExpireTime: 300
# RefreshToken过期时间-30分钟-30*60(秒为单位)
refreshTokenExpireTime: 1800
# Shiro缓存过期时间-5分钟-5*60(秒为单位)(一般设置与AccessToken过期时间一致)
shiroCacheExpireTime: 300